/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ızubus;

import java.sql.*;
import java.awt.Color;

    

public class Giris extends javax.swing.JFrame {
public static String ogr_no;
    Connection con;
    PreparedStatement st;
    ResultSet rs;
    ResultSetMetaData stData;
    
    public Giris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        pnl_giris_sol = new javax.swing.JPanel();
        lb_icon_izubus = new javax.swing.JLabel();
        lb_izubus = new javax.swing.JLabel();
        pnl_giris_sag = new javax.swing.JPanel();
        lb_cıkıs = new javax.swing.JLabel();
        lb_giris_yap = new javax.swing.JLabel();
        lb_ogrenci_numara = new javax.swing.JLabel();
        lb_alt_cizgi = new javax.swing.JLabel();
        lb_icon_ogrenci_numara = new javax.swing.JLabel();
        lb_sifre = new javax.swing.JLabel();
        lb_icon_ogrenci_sifre = new javax.swing.JLabel();
        ch_sifreyi_hatırla = new javax.swing.JCheckBox();
        lb_sifremi_unuttum = new javax.swing.JLabel();
        btn_giris_yap = new javax.swing.JButton();
        lb_alt_cizgi2 = new javax.swing.JLabel();
        txt_ogrenci_numara = new javax.swing.JTextField();
        psw_ogrenci_sifre = new javax.swing.JPasswordField();
        lb_icon_ogrenci_sifre2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_giris_sol.setBackground(new java.awt.Color(255, 255, 255));

        lb_icon_izubus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_icon_izubus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bus.png"))); // NOI18N
        lb_icon_izubus.setFocusable(false);

        lb_izubus.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lb_izubus.setForeground(new java.awt.Color(25, 118, 214));
        lb_izubus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_izubus.setText("IZUBUS");

        javax.swing.GroupLayout pnl_giris_solLayout = new javax.swing.GroupLayout(pnl_giris_sol);
        pnl_giris_sol.setLayout(pnl_giris_solLayout);
        pnl_giris_solLayout.setHorizontalGroup(
            pnl_giris_solLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_giris_solLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pnl_giris_solLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_izubus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_icon_izubus, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnl_giris_solLayout.setVerticalGroup(
            pnl_giris_solLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_giris_solLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_izubus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lb_icon_izubus, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        getContentPane().add(pnl_giris_sol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 450));

        pnl_giris_sag.setBackground(new java.awt.Color(25, 118, 214));
        pnl_giris_sag.setForeground(new java.awt.Color(255, 255, 255));
        pnl_giris_sag.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_cıkıs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_cıkıs.setForeground(new java.awt.Color(255, 255, 255));
        lb_cıkıs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_cıkıs.setText("X");
        lb_cıkıs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_cıkıs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_cıkısMouseClicked(evt);
            }
        });
        pnl_giris_sag.add(lb_cıkıs, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 40, -1));

        lb_giris_yap.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lb_giris_yap.setForeground(new java.awt.Color(255, 255, 255));
        lb_giris_yap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_giris_yap.setText("Giriş Yap");
        pnl_giris_sag.add(lb_giris_yap, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, 351, -1));

        lb_ogrenci_numara.setForeground(new java.awt.Color(199, 226, 255));
        lb_ogrenci_numara.setText("Öğrenci Numarası");
        pnl_giris_sag.add(lb_ogrenci_numara, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 125, -1));

        lb_alt_cizgi.setForeground(new java.awt.Color(255, 255, 255));
        lb_alt_cizgi.setText("_____________________________________________________________");
        lb_alt_cizgi.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnl_giris_sag.add(lb_alt_cizgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 295, 20));

        lb_icon_ogrenci_numara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_20px_1.png"))); // NOI18N
        pnl_giris_sag.add(lb_icon_ogrenci_numara, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 20, 29));

        lb_sifre.setForeground(new java.awt.Color(199, 226, 255));
        lb_sifre.setText("Şifre");
        pnl_giris_sag.add(lb_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 202, -1));

        lb_icon_ogrenci_sifre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_invisible_20px_1.png"))); // NOI18N
        lb_icon_ogrenci_sifre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_icon_ogrenci_sifreMouseClicked(evt);
            }
        });
        pnl_giris_sag.add(lb_icon_ogrenci_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 30, 30));

        ch_sifreyi_hatırla.setBackground(new java.awt.Color(25, 118, 214));
        ch_sifreyi_hatırla.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ch_sifreyi_hatırla.setForeground(new java.awt.Color(199, 226, 255));
        ch_sifreyi_hatırla.setText("Şifreyi Hatırla");
        ch_sifreyi_hatırla.setMargin(new java.awt.Insets(2, 0, 2, 2));
        ch_sifreyi_hatırla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_sifreyi_hatırlaActionPerformed(evt);
            }
        });
        pnl_giris_sag.add(ch_sifreyi_hatırla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 110, -1));

        lb_sifremi_unuttum.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lb_sifremi_unuttum.setForeground(new java.awt.Color(199, 226, 255));
        lb_sifremi_unuttum.setText("Şifremi Unuttum");
        lb_sifremi_unuttum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_giris_sag.add(lb_sifremi_unuttum, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 100, -1));

        btn_giris_yap.setBackground(new java.awt.Color(255, 255, 255));
        btn_giris_yap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_giris_yap.setForeground(new java.awt.Color(25, 118, 214));
        btn_giris_yap.setText("Giriş Yap");
        btn_giris_yap.setBorder(null);
        btn_giris_yap.setBorderPainted(false);
        btn_giris_yap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_giris_yap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_giris_yapMouseClicked(evt);
            }
        });
        btn_giris_yap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giris_yapActionPerformed(evt);
            }
        });
        pnl_giris_sag.add(btn_giris_yap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 330, 40));

        lb_alt_cizgi2.setForeground(new java.awt.Color(255, 255, 255));
        lb_alt_cizgi2.setText("_____________________________________________________________");
        lb_alt_cizgi2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pnl_giris_sag.add(lb_alt_cizgi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 295, 10));

        txt_ogrenci_numara.setBackground(new java.awt.Color(25, 118, 214));
        txt_ogrenci_numara.setBorder(null);
        txt_ogrenci_numara.setMargin(new java.awt.Insets(2, 0, 2, 6));
        txt_ogrenci_numara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ogrenci_numaraActionPerformed(evt);
            }
        });
        pnl_giris_sag.add(txt_ogrenci_numara, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 290, -1));

        psw_ogrenci_sifre.setBackground(new java.awt.Color(25, 118, 214));
        psw_ogrenci_sifre.setBorder(null);
        psw_ogrenci_sifre.setOpaque(true);
        psw_ogrenci_sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psw_ogrenci_sifreActionPerformed(evt);
            }
        });
        pnl_giris_sag.add(psw_ogrenci_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 264, 290, -1));

        lb_icon_ogrenci_sifre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_eye_20px_1.png"))); // NOI18N
        lb_icon_ogrenci_sifre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_icon_ogrenci_sifre2MouseClicked(evt);
            }
        });
        pnl_giris_sag.add(lb_icon_ogrenci_sifre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 30, 30));

        getContentPane().add(pnl_giris_sag, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 440, 450));

        setSize(new java.awt.Dimension(899, 447));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ch_sifreyi_hatırlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_sifreyi_hatırlaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_sifreyi_hatırlaActionPerformed

    private void lb_cıkısMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_cıkısMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lb_cıkısMouseClicked

    private void psw_ogrenci_sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psw_ogrenci_sifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psw_ogrenci_sifreActionPerformed

    private void lb_icon_ogrenci_sifreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_icon_ogrenci_sifreMouseClicked
psw_ogrenci_sifre.setEchoChar((char)0);
lb_icon_ogrenci_sifre.setVisible(false);
lb_icon_ogrenci_sifre.setEnabled(false);
lb_icon_ogrenci_sifre2.setVisible(true);
lb_icon_ogrenci_sifre2.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_lb_icon_ogrenci_sifreMouseClicked

    private void lb_icon_ogrenci_sifre2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_icon_ogrenci_sifre2MouseClicked
        psw_ogrenci_sifre.setEchoChar((char)8226);
lb_icon_ogrenci_sifre.setVisible(true);
lb_icon_ogrenci_sifre.setEnabled(true);
lb_icon_ogrenci_sifre2.setVisible(false);
lb_icon_ogrenci_sifre2.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_lb_icon_ogrenci_sifre2MouseClicked

    private void btn_giris_yapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giris_yapActionPerformed

        
        

      try{
          con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/deneme", "root", "1234");
          st = con.prepareStatement("select * from ogrenci_bilgisi");
           rs = st.executeQuery();
           while(rs.next()){
               
               if(rs.getString("ogr_numarası").equals(txt_ogrenci_numara.getText()) && rs.getString("parola").equals(psw_ogrenci_sifre.getText()))
               {
                   System.out.print(rs.getString("eposta"));
               ogr_no = txt_ogrenci_numara.getText();
               this.setVisible(false);
               AnaMenu s = new AnaMenu(rs);
               s.setVisible(true);
           }
           } 
           rs.close();
            st.close();
            con.close();
           
    }                                          
    catch(SQLException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_giris_yapActionPerformed

    private void txt_ogrenci_numaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ogrenci_numaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ogrenci_numaraActionPerformed

    private void btn_giris_yapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_giris_yapMouseClicked
 /*     try{
          con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/deneme", "root", "1234");
          st = con.prepareStatement("select * from ogrenci_bilgisi");
           rs = st.executeQuery();
           if(rs.next()){
               System.out.println(rs.getString("ogr_numarası") + " - " + rs.getString("parola"));
           }
           rs.close();
            st.close();
            con.close();
           
    }//GEN-LAST:event_btn_giris_yapMouseClicked
    catch(SQLException e)
        {
            e.printStackTrace();
        }
        */
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_giris_yap;
    private javax.swing.JCheckBox ch_sifreyi_hatırla;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lb_alt_cizgi;
    private javax.swing.JLabel lb_alt_cizgi2;
    private javax.swing.JLabel lb_cıkıs;
    private javax.swing.JLabel lb_giris_yap;
    private javax.swing.JLabel lb_icon_izubus;
    private javax.swing.JLabel lb_icon_ogrenci_numara;
    private javax.swing.JLabel lb_icon_ogrenci_sifre;
    private javax.swing.JLabel lb_icon_ogrenci_sifre2;
    private javax.swing.JLabel lb_izubus;
    private javax.swing.JLabel lb_ogrenci_numara;
    private javax.swing.JLabel lb_sifre;
    private javax.swing.JLabel lb_sifremi_unuttum;
    private javax.swing.JPanel pnl_giris_sag;
    private javax.swing.JPanel pnl_giris_sol;
    public javax.swing.JPasswordField psw_ogrenci_sifre;
    public javax.swing.JTextField txt_ogrenci_numara;
    // End of variables declaration//GEN-END:variables
}
